### ISSUE TITLE
Not possible to copy an activity from the sharing cart if it comes from the frontpage

### ISSUE THREAD

**Issue by Julian-Tovar** [donhinkelman/moodle-block_sharing_cart#227]
Good day team.

When one has activities on the frontpage, and one adds them to the sharing cart, then copying these activities into a course produces and error.

Even before listing the steps to replicate, let me share an image of the error itself:

<img width="1654" alt="Screenshot 2024-12-19 at 5 02 44 PM" src="https://github.com/user-attachments/assets/24825e33-9ae6-431d-b33b-19cd6b0f37d0" />

Just in case, this is the plain text version of the error:

``` error
restore_step_exception: Backup is missing XML file: [backuptempdir]//0d0d370948de27a70eefdb88135dad00/activities/assign_2/grades.xml in [dirroot]/backup/util/plan/restore_structure_step.class.php:80 
Stack trace:
#0 [dirroot]/backup/util/plan/base_task.class.php(186): restore_structure_step-&gt;execute()
#1 [dirroot]/backup/moodle2/restore_activity_task.class.php(224): base_task-&gt;execute()
#2 [dirroot]/backup/util/plan/base_plan.class.php(191): restore_activity_task-&gt;execute()
#3 [dirroot]/backup/util/plan/restore_plan.class.php(168): base_plan-&gt;execute()
#4 [dirroot]/backup/controller/restore_controller.class.php(411): restore_plan-&gt;execute()
#5 [dirroot]/blocks/sharing_cart/classes/controller.php(716): restore_controller-&gt;execute_plan()
#6 [dirroot]/blocks/sharing_cart/restore.php(95): block_sharing_cart\controller-&gt;restore(1, 2, 0)
#7 {main}

Stack trace:
line 112 of /blocks/sharing_cart/restore.php: moodle_exception thrown
```

Now here for the steps to replicate

**Preconditions**

1. Have a Moodle site on 4.4, 4.5 or 4.6.
2. Install and enable the block_sharing_cart plugin.
3. Use the Boost theme.

**Steps to replicate**

1. Log in as admin.
2. Go to the frontpage.
4. Activate edit mode.
5. Add the Sharing Cart block to the frontpage.
6. Create an activity (an Assignment for example).
7. Add the activity created to the Sharing Cart on the frontpage.
8. Create or go to a course.
9. Add the Sharing Cart block to the course.
10. Verify that on the Sharing Cart block, the assignment from the frontpage appears.
11. Click on the "copy" icon to copy the assignment from the frontpage into the course.
12. Click on the arrow to place the copied assignment in the course.

**Observed behavior**

The error shown appears.

**Expected behavior**

The copied activity from step 12 appears correctly and is made part of the course

**Comment by Julian-Tovar** [comment]
Using the code from the default branch of this project https://github.com/donhinkelman/moodle-block_sharing_cart/tree/master this problem looks a bit different but it's still there:

<img width="314" alt="Screenshot 2024-12-23 at 1 17 22 PM" src="https://github.com/user-attachments/assets/5e42cd51-b561-4744-bd6a-16d39892e802" />

As you can see, the activities are left in a restore state which never progresses, even if the cron is executed and all available scheduled and adhoc tasks are run.
